language: python
python:
  - '3.8.0'

dist: trusty
addons:
  chrome: stable
  
before_script:
  - pipenv install
  - wget http://chromedriver.storage.googleapis.com/87.0.4280.88/chromedriver_mac64.zip
  - unzip chromedriver_mac64.zip -d /home/travis/virtualenv/python3.8.0/bin/
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 

env: DJANGO_SETTINGS_MODULE="purbeurre.settings.travis"

services:
  - postgresql

script:
  - ./manage.py test