addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver

language: python
python:
  - '3.8.0'

dist: xenial
services:
  - postgresql
  - xvfb

before_script:

 - pipenv install
 # Added to properly run selenium functional test
 - wget http://chromedriver.storage.googleapis.com/87.0.4280.88/chromedriver_linux64.zip
 - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.8.0/
 - export CHROME_BIN=chromium-browser
 - "export DISPLAY=:99.0"
 - sleep 3 
  

env: DJANGO_SETTINGS_MODULE="purbeurre.settings.travis"




script:
  - ./manage.py test

