language: python
python:
  - '3.8.0'

before_script:
  - pipenv install
  - pipenv install linuxbrew-wrapper
  - brew install --cask chromedriver
  

env: DJANGO_SETTINGS_MODULE="purbeurre.settings.travis"

services:
  - postgresql

script:
  - ./manage.py test
