addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver

language: python
python:
  - '3.8.0'

dist: xenial
services:
  - postgresql
  - xvfb

before_script:

 - pipenv install
 - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
 - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 3 
  

env: DJANGO_SETTINGS_MODULE="purbeurre.settings.travis"




script:
  - ./manage.py test

