addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
      
language: python
python:
  - '3.8.0'

before_script:

 - pipenv install
 - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
 - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

  

env: DJANGO_SETTINGS_MODULE="purbeurre.settings.travis"

services:
  - postgresql

script:
  - ./manage.py test

